---@diagnostic disable: codestyle-check

---Base class XTumbleweed
---@class XTumbleweed
---@field settings {["abr"]: number|integer}
---@field spawn_reduction number|integer
---@field spawn_rate number|integer
---@field register_entity fun(self: XTumbleweed, name: string, def: table)
---@field brainfunc fun(self: XTumbleweed, selfObj: table)
---@field on_punch fun(self: table, selfObj: table,  puncher: ObjectRef|nil, time_from_last_punch: number|integer|nil, tool_capabilities: ToolCapabilitiesDef|nil, dir: Vector, damage: number|integer): boolean|nil
---@field globalstep fun(self: XTumbleweed, dtime: number|integer)
